// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuthapitafnzlktbbkdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dGhhcGl0YWZuemxrdGJia2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDU3NjUsImV4cCI6MjA3MjYyMTc2NX0.mdf7tLKFpWTPvFpcy0w56MGLwrzHDaJw9z0Yianc2ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});